name: Deploy Monorepo Services

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-user-service:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy user-service
        working-directory: root-folder/user-service
        run: |
          npm ci
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
          serverless deploy --verbose

  deploy-product-service:
    runs-on: self-hosted
    needs: deploy-user-service
    steps:
      - uses: actions/checkout@v4
      - name: Deploy product-service
        working-directory: root-folder/product-service
        run: |
          npm ci
          cdk deploy --require-approval never --verbose

  deploy-transaction-service:
    runs-on: self-hosted
    needs: deploy-product-service
    steps:
      - uses: actions/checkout@v4
      - name: Deploy transaction-service
        working-directory: root-folder/transaction-service
        run: |
          npm ci
          cdk deploy --require-approval never --verbose
