name: Node.js Monorepo CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  user-service:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: root-folder/user-service
    

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: root-folder/user-service/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Inject .env file
        run: |
          echo "${{ secrets.PROD_ENV_FILE }}" | base64 -d > .env


      - name: Deploy user-service
        run: SERVERLESS_DASHBOARD=0 npx serverless deploy --verbose

  product-service:
    runs-on: self-hosted
    needs: user-service
    defaults:
      run:
        working-directory: root-folder/product-service
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: root-folder/product-service/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Deploy product-service
        run: npx cdk deploy --require-approval never --verbose

  transaction-service:
    runs-on: self-hosted
    needs: product-service
    defaults:
      run:
        working-directory: root-folder/transaction-service
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: root-folder/transaction-service/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Deploy transaction-service
        run: npx cdk deploy --require-approval never --verbose
