name: Node.js Monorepo CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  user-service:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: root-folder/user-service
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy user-service
        run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
          npx serverless deploy --verbose

  product-service:
    runs-on: self-hosted
    needs: user-service
    defaults:
      run:
        working-directory: root-folder/product-service
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy product-service
        run: npx cdk deploy --require-approval never --verbose

  transaction-service:
    runs-on: self-hosted
    needs: product-service
    defaults:
      run:
        working-directory: root-folder/transaction-service
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy transaction-service
        run: npx cdk deploy --require-approval never --verbose
